name: Build FOSS APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build FOSS Release APK
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup project and build environment
        uses: ./.github/actions/common-setup

      - name: Decode and setup keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
        run: |
          mkdir -p $HOME/.android
          echo "$ENCODED_KEYSTORE" | base64 -d > $HOME/.android/release.jks
          echo "Keystore file created at: $HOME/.android/release.jks"
          ls -lh $HOME/.android/release.jks

      - name: Build FOSS Release APK
        run: ./gradlew assembleFossRelease
        env:
          STORE_PATH: ${{ runner.temp }}/.android/release.jks
          STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        continue-on-error: false

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: app/build/outputs/apk/foss/release/*.apk
          tag_name: build-${{ github.run_number }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: foss-apk
          path: app/build/outputs/apk/foss/release/*.apk
          retention-days: 30
